

package cloudsim;
simple Broker
{
 parameters:
   
    	
      	
        @display("i=device/server");
        
        gates:
        
        input in1 ;
        input in2;
        input in3 ;
        input in4;
        input in5 ;
     
      
        output out1;
        output out2;
        output out3;
        output out4;
        output out5;
       output out6;
        output out7;
        output out8;
        output out9;
        output out10;
     
}